name: Spelling Check

on:
  pull_request:

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Spelling Check
        uses: crate-ci/typos@master
        with:
          files: |
            crates
            sdk
            scripts
          config: typos.toml
